# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cracker2.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 417)
        MainWindow.setMinimumSize(QtCore.QSize(680, 417))
        MainWindow.setMaximumSize(QtCore.QSize(680, 417))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 401, 321))
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setOverwriteMode(False)
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_Control_Panel = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Control_Panel.setGeometry(QtCore.QRect(420, 20, 251, 331))
        self.groupBox_Control_Panel.setObjectName("groupBox_Control_Panel")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_Control_Panel)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 251, 324))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_open = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_2.addWidget(self.btn_open)
        self.btn_save = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(10, 0, 10, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_lang = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_lang.setObjectName("comboBox_lang")
        self.comboBox_lang.addItem("")
        self.comboBox_lang.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_lang)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_method = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_method.setObjectName("comboBox_method")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_method)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.checkBox_skip = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_skip.setObjectName("checkBox_skip")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox_skip)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setVerticalSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox.setMinimum(2)
        self.spinBox.setProperty("value", 3)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.spinBox)
        self.spinBox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_2.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_2.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_2.setMinimum(2)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.spinBox_2)
        self.spin_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.spin_label_2.setObjectName("spin_label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_label_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_3)
        self.spin_label_1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.spin_label_1.setObjectName("spin_label_1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin_label_1)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.formLayout_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btn_start = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout.addWidget(self.btn_start)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressbar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressbar.setGeometry(QtCore.QRect(10, 360, 661, 16))
        self.progressbar.setProperty("value", 0)
        self.progressbar.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.progressbar.setTextVisible(False)
        self.progressbar.setObjectName("progressbar")
        self.progress_label = QtWidgets.QLabel(self.centralwidget)
        self.progress_label.setGeometry(QtCore.QRect(10, 360, 661, 16))
        self.progress_label.setText("")
        self.progress_label.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_label.setObjectName("progress_label")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(340, 10, 71, 20))
        self.btn_clear.setAutoDefault(False)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(160, 10, 176, 21))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_fs = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_fs.setObjectName("label_fs")
        self.gridLayout.addWidget(self.label_fs, 0, 0, 1, 1)
        self.slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.slider.setMinimumSize(QtCore.QSize(85, 0))
        self.slider.setMaximumSize(QtCore.QSize(50, 15))
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.gridLayout.addWidget(self.slider, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGuide_to_Vigenere_s_Cipher = QtWidgets.QAction(MainWindow)
        self.actionGuide_to_Vigenere_s_Cipher.setObjectName("actionGuide_to_Vigenere_s_Cipher")
        self.actionAuthor_License = QtWidgets.QAction(MainWindow)
        self.actionAuthor_License.setObjectName("actionAuthor_License")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuHelp.addAction(self.actionGuide_to_Vigenere_s_Cipher)
        self.menuHelp.addAction(self.actionAuthor_License)
        self.menuHelp.addAction(self.actionExit)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.checkBox_skip.toggled['bool'].connect(self.spin_label_2.setHidden)
        self.checkBox_skip.toggled['bool'].connect(self.spinBox.setHidden)
        self.checkBox_skip.toggled['bool'].connect(self.spinBox_2.setHidden)
        self.checkBox_skip.toggled['bool'].connect(self.spin_label_1.setHidden)
        self.actionExit.triggered['bool'].connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VCC 1.9.0. by Bartosz Grabek "))
        self.label.setText(_translate("MainWindow", "Ciphergram:"))
        self.groupBox_Control_Panel.setTitle(_translate("MainWindow", "Control Panel"))
        self.btn_open.setText(_translate("MainWindow", "Open"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
        self.label_3.setText(_translate("MainWindow", "Settings:"))
        self.label_2.setText(_translate("MainWindow", "Language"))
        self.comboBox_lang.setItemText(0, _translate("MainWindow", "English"))
        self.comboBox_lang.setItemText(1, _translate("MainWindow", "Polish"))
        self.label_4.setText(_translate("MainWindow", "Method"))
        self.comboBox_method.setItemText(0, _translate("MainWindow", "Statistic (one key, simple)"))
        self.comboBox_method.setItemText(1, _translate("MainWindow", "Statistic (multiple keys)"))
        self.checkBox_skip.setText(_translate("MainWindow", "Skip key length search"))
        self.spin_label_2.setToolTip(_translate("MainWindow", "# minimal number of appearings of repeating fragments to find"))
        self.spin_label_2.setText(_translate("MainWindow", "MIN_CNT"))
        self.spin_label_1.setToolTip(_translate("MainWindow", "# minimal length of repeating fragments to find"))
        self.spin_label_1.setText(_translate("MainWindow", "MIN_LEN"))
        self.btn_start.setText(_translate("MainWindow", "Crack"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.label_fs.setText(_translate("MainWindow", "Font size:  14 "))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionGuide_to_Vigenere_s_Cipher.setText(_translate("MainWindow", "Guide to Vigenere\'s Cipher"))
        self.actionAuthor_License.setText(_translate("MainWindow", "Author/License"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Esc"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
