# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frajer.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(961, 418)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(540, 10, 411, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(540, 90, 181, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listwidget_lengths = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.listwidget_lengths.setObjectName("listwidget_lengths")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listwidget_lengths.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listwidget_lengths.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listwidget_lengths.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listwidget_lengths.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listwidget_lengths.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listwidget_lengths.addItem(item)
        self.verticalLayout_2.addWidget(self.listwidget_lengths)
        self.checkbox_use_dict = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkbox_use_dict.setChecked(True)
        self.checkbox_use_dict.setObjectName("checkbox_use_dict")
        self.verticalLayout_2.addWidget(self.checkbox_use_dict)
        self.btn_get_passwords = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_get_passwords.setObjectName("btn_get_passwords")
        self.verticalLayout_2.addWidget(self.btn_get_passwords)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(740, 90, 211, 301))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.list_passwords = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        self.list_passwords.setEnabled(False)
        self.list_passwords.setObjectName("list_passwords")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_passwords.addItem(item)
        self.verticalLayout_3.addWidget(self.list_passwords)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radiobtn_auto = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radiobtn_auto.setEnabled(False)
        self.radiobtn_auto.setChecked(True)
        self.radiobtn_auto.setObjectName("radiobtn_auto")
        self.horizontalLayout.addWidget(self.radiobtn_auto)
        self.radiobtn_manual = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radiobtn_manual.setEnabled(False)
        self.radiobtn_manual.setObjectName("radiobtn_manual")
        self.horizontalLayout.addWidget(self.radiobtn_manual)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_cancel = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_cancel.setEnabled(False)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.btn_check = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_check.setEnabled(False)
        self.btn_check.setObjectName("btn_check")
        self.horizontalLayout_2.addWidget(self.btn_check)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 371, 381))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.table_widget_calc = QtWidgets.QTableWidget(self.verticalLayoutWidget_4)
        self.table_widget_calc.setObjectName("table_widget_calc")
        self.table_widget_calc.setColumnCount(0)
        self.table_widget_calc.setRowCount(0)
        self.verticalLayout_4.addWidget(self.table_widget_calc)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(390, 10, 131, 381))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.table_widget_keys = QtWidgets.QTableWidget(self.verticalLayoutWidget_5)
        self.table_widget_keys.setObjectName("table_widget_keys")
        self.table_widget_keys.setColumnCount(0)
        self.table_widget_keys.setRowCount(0)
        self.verticalLayout_5.addWidget(self.table_widget_keys)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(9, 11, 511, 381))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_7)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setAcceptDrops(True)
        self.textBrowser.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.textBrowser.setUndoRedoEnabled(False)
        self.textBrowser.setOpenLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_7.addWidget(self.textBrowser)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(540, 280, 181, 111))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_9.setEnabled(False)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_left = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.btn_left.setEnabled(False)
        self.btn_left.setObjectName("btn_left")
        self.horizontalLayout_3.addWidget(self.btn_left)
        self.btn_right = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.btn_right.setEnabled(False)
        self.btn_right.setObjectName("btn_right")
        self.horizontalLayout_3.addWidget(self.btn_right)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.line_password_static = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.line_password_static.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line_password_static.setFont(font)
        self.line_password_static.setToolTip("")
        self.line_password_static.setWhatsThis("")
        self.line_password_static.setAccessibleName("")
        self.line_password_static.setAccessibleDescription("")
        self.line_password_static.setInputMask("")
        self.line_password_static.setText("")
        self.line_password_static.setMaxLength(50)
        self.line_password_static.setAlignment(QtCore.Qt.AlignCenter)
        self.line_password_static.setReadOnly(True)
        self.line_password_static.setObjectName("line_password_static")
        self.verticalLayout_8.addWidget(self.line_password_static)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_cancel2 = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.btn_cancel2.setEnabled(False)
        self.btn_cancel2.setObjectName("btn_cancel2")
        self.horizontalLayout_4.addWidget(self.btn_cancel2)
        self.btn_ok2 = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.btn_ok2.setEnabled(False)
        self.btn_ok2.setObjectName("btn_ok2")
        self.horizontalLayout_4.addWidget(self.btn_ok2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)

        self.progressbar_2 = QtWidgets.QProgressBar(Form)
        self.progressbar_2.setGeometry(QtCore.QRect(10, 390, 511, 16))
        self.progressbar_2.setProperty("value", 0)
        self.progressbar_2.setAlignment(QtCore.Qt.AlignCenter)
        self.progressbar_2.setObjectName("progressbar_2")

        #
        self.progressbar_2.hide()
        self.textBrowser.hide()
        self.label_8.hide()
        #

        self.retranslateUi(Form)
        self.btn_get_passwords.clicked['bool'].connect(self.list_passwords.setDisabled)
        self.btn_get_passwords.clicked['bool'].connect(self.radiobtn_auto.setDisabled)
        self.btn_get_passwords.clicked['bool'].connect(self.radiobtn_manual.setDisabled)
        self.btn_get_passwords.clicked['bool'].connect(self.btn_cancel.setDisabled)
        self.btn_get_passwords.clicked['bool'].connect(self.label_7.setDisabled)
        self.btn_get_passwords.clicked['bool'].connect(self.label_3.setDisabled)
        self.btn_get_passwords.clicked['bool'].connect(self.btn_check.setDisabled)
        self.btn_get_passwords.clicked['bool'].connect(self.btn_get_passwords.setEnabled)
        self.btn_cancel.clicked['bool'].connect(self.btn_get_passwords.setDisabled)
        self.btn_cancel.clicked['bool'].connect(self.radiobtn_auto.setEnabled)
        self.btn_cancel.clicked['bool'].connect(self.radiobtn_manual.setEnabled)
        self.btn_cancel.clicked['bool'].connect(self.label_3.setEnabled)
        self.btn_cancel.clicked['bool'].connect(self.label_7.setEnabled)
        self.btn_cancel.clicked['bool'].connect(self.btn_check.setEnabled)
        self.btn_cancel.clicked['bool'].connect(self.list_passwords.clear)
        self.btn_cancel.clicked['bool'].connect(self.list_passwords.setEnabled)
        self.btn_cancel.clicked['bool'].connect(self.btn_cancel.setEnabled)
        self.btn_get_passwords.clicked['bool'].connect(self.checkbox_use_dict.setEnabled)
        self.btn_get_passwords.clicked['bool'].connect(self.listwidget_lengths.setEnabled)
        self.btn_cancel.clicked['bool'].connect(self.listwidget_lengths.setDisabled)
        self.btn_cancel.clicked['bool'].connect(self.checkbox_use_dict.setDisabled)
        self.btn_cancel.clicked['bool'].connect(self.label_2.setDisabled)
        self.btn_get_passwords.clicked['bool'].connect(self.label_2.setEnabled)
        self.btn_cancel.clicked['bool'].connect(self.textBrowser.hide)
        self.btn_get_passwords.clicked['bool'].connect(self.label_5.hide)
        self.btn_get_passwords.clicked['bool'].connect(self.table_widget_calc.hide)
        self.btn_get_passwords.clicked['bool'].connect(self.table_widget_keys.hide)
        self.btn_get_passwords.clicked['bool'].connect(self.label_4.hide)
        self.btn_get_passwords.clicked['bool'].connect(self.textBrowser.show)
        self.btn_get_passwords.clicked['bool'].connect(self.label_8.show)
        self.btn_cancel.clicked['bool'].connect(self.label_8.hide)
        self.btn_cancel.clicked['bool'].connect(self.table_widget_keys.show)
        self.btn_cancel.clicked['bool'].connect(self.table_widget_calc.show)
        self.btn_cancel.clicked['bool'].connect(self.label_4.show)
        self.btn_cancel.clicked['bool'].connect(self.label_5.show)
        self.btn_check.clicked['bool'].connect(self.label_9.setDisabled)
        self.btn_check.clicked['bool'].connect(self.btn_left.setDisabled)
        self.btn_check.clicked['bool'].connect(self.btn_right.setDisabled)
        self.btn_check.clicked['bool'].connect(self.btn_cancel2.setDisabled)
        self.btn_check.clicked['bool'].connect(self.btn_ok2.setDisabled)
        self.btn_cancel.clicked['bool'].connect(self.btn_ok2.setEnabled)
        self.btn_cancel.clicked['bool'].connect(self.btn_cancel2.setEnabled)
        self.btn_cancel.clicked['bool'].connect(self.btn_left.setEnabled)
        self.btn_cancel.clicked['bool'].connect(self.btn_right.setEnabled)
        self.btn_cancel.clicked['bool'].connect(self.line_password_static.clear)
        self.btn_cancel2.clicked['bool'].connect(self.btn_left.setEnabled)
        self.btn_cancel2.clicked['bool'].connect(self.btn_right.setEnabled)
        self.btn_cancel2.clicked['bool'].connect(self.line_password_static.clear)
        self.btn_cancel2.clicked['bool'].connect(self.btn_ok2.setEnabled)
        self.btn_cancel2.clicked['bool'].connect(self.btn_cancel2.setEnabled)
        self.btn_check.clicked['bool'].connect(self.radiobtn_auto.setEnabled)
        self.btn_check.clicked['bool'].connect(self.radiobtn_manual.setEnabled)
        self.btn_check.clicked['bool'].connect(self.btn_cancel.setEnabled)
        self.btn_check.clicked['bool'].connect(self.label_7.setEnabled)
        self.btn_check.clicked['bool'].connect(self.list_passwords.setEnabled)
        self.btn_check.clicked['bool'].connect(self.label_3.setEnabled)
        self.btn_check.clicked['bool'].connect(self.btn_check.setEnabled)
        self.btn_cancel2.clicked['bool'].connect(self.btn_check.setDisabled)
        self.btn_cancel2.clicked['bool'].connect(self.btn_cancel.setDisabled)
        self.btn_cancel2.clicked['bool'].connect(self.radiobtn_auto.setDisabled)
        self.btn_cancel2.clicked['bool'].connect(self.list_passwords.setDisabled)
        self.btn_cancel2.clicked['bool'].connect(self.label_7.setDisabled)
        self.btn_cancel2.clicked['bool'].connect(self.label_3.setDisabled)
        self.btn_cancel2.clicked['bool'].connect(self.radiobtn_manual.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "INFORMATION"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "1. Choose length(s) of password:"))
        __sortingEnabled = self.listwidget_lengths.isSortingEnabled()
        self.listwidget_lengths.setSortingEnabled(False)
        item = self.listwidget_lengths.item(0)
        item.setText(_translate("Form", "Zaznacz wszystko"))
        item = self.listwidget_lengths.item(1)
        item.setText(_translate("Form", "2"))
        item = self.listwidget_lengths.item(2)
        item.setText(_translate("Form", "3"))
        item = self.listwidget_lengths.item(3)
        item.setText(_translate("Form", "5"))
        item = self.listwidget_lengths.item(4)
        item.setText(_translate("Form", "10"))
        item = self.listwidget_lengths.item(5)
        item.setText(_translate("Form", "15"))
        self.listwidget_lengths.setSortingEnabled(__sortingEnabled)
        self.checkbox_use_dict.setText(_translate("Form", "Search only for dictionary words"))
        self.btn_get_passwords.setText(_translate("Form", "Get probable passwords"))
        self.label_3.setText(_translate("Form", "2. Choose password(s) to check:"))
        __sortingEnabled = self.list_passwords.isSortingEnabled()
        self.list_passwords.setSortingEnabled(False)
        item = self.list_passwords.item(0)
        item.setText(_translate("Form", "Zaznacz wszystko"))
        self.list_passwords.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(_translate("Form", "Choose method"))
        self.radiobtn_auto.setText(_translate("Form", "Auto (recommended)"))
        self.radiobtn_manual.setText(_translate("Form", "Manual"))
        self.btn_cancel.setText(_translate("Form", "Cancel"))
        self.btn_check.setText(_translate("Form", "Check"))
        self.label_4.setText(_translate("Form", "Calculation table"))
        self.label_5.setText(_translate("Form", "Possible keys"))
        self.label_8.setText(_translate("Form", "Ciphergram"))
        self.label_9.setText(_translate("Form", "3. Password finder"))
        self.btn_left.setText(_translate("Form", "<"))
        self.btn_right.setText(_translate("Form", ">"))
        self.line_password_static.setPlaceholderText(_translate("Form", "PASSWORD"))
        self.btn_cancel2.setText(_translate("Form", "Cancel"))
        self.btn_ok2.setText(_translate("Form", "OK"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
